apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgresql
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: POSTGRESQL_PASSWORD
  POSTGRESQL_USERNAME: POSTGRESQL_USERNAME
  POSTGRESQL_DATABASE: POSTGRESQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql-cluster-ip
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: keycloak-postgresql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgresql
  template:
    metadata:
      labels:
        app: keycloak-postgresql
    spec:
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: keycloak-postgresql
      containers:
        - name: postgresql
          image: bitnami/postgresql
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-storage
              mountPath: /bitnami/postgresql
              subPath: postgresql
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRESQL_USERNAME
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRESQL_PASSWORD
