apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Auth-Request-Preferred-Username, X-Forwarded-Access-Token, X-Forwarded-User, X-Forwarded-Email, X-Forwarded-Preferred-Username"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: nginx-cluster-ip
              servicePort: 8080
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-ip
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: brndnmtthws/nginx-echo-headers
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
