apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-redis-cluster-ip
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: oauth2-proxy-redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy-redis
  template:
    metadata:
      labels:
        app: oauth2-proxy-redis
    spec:
      containers:
        - name: oauth2-proxy-redis
          image: bitnami/redis
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
